// <auto-generated />
namespace Single_Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newnewnew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newnewnew));
        
        string IMigrationMetadata.Id
        {
            get { return "202002031644200_newnewnew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
